local libnvml = require('nvml')
print(hello())
print(nvml_is_initialized())
nvml_init()
print(nvml_is_initialized(3))
nvml_init()
print(nvml_is_initialized(1, 2, 3))
print(nvml_num_devices())
local n = nvml_num_devices()
print(n)

local data = nvml_query_device_info(0)
print(data)
print('name: ' .. data['name'])
print('fan speed: ' .. data['fanSpeedPercent'] .. '%')
print('Core freq: ' .. data['freq'] .. 'MHz')
print('Memory freq: ' .. data['memFreq'] .. 'MHz')
print('Temp: ' .. data['tempCelcius'] .. 'C')
print('Throttle Temp: ' .. data['slowdownTempCelcius'] .. 'C')
print('Shutdown Temp: ' .. data['shutdownTempCelcius'] .. 'C')
-- print(nvml_query_device_info('ea', 3))
nvml_close()
nvml_close()
print(nvml_is_initialized(1, 2, 3))
