local nvml = require('nvml')
nvml.init()
print("Is init: " .. tostring(nvml.is_initialized(3)))
print("Is init: " .. tostring(nvml.is_initialized(1, 2, 3)))
print(nvml.num_devices())
local n = nvml.num_devices()
print(n)

for i = 0, n-1 do
    local data = nvml.query_device_info(i)
    print('Response ' .. tostring(i) .. ': ' .. tostring(data))
    print('name: ' .. data['name'])
    print('fan speed: ' .. data['fanSpeedPercent'] .. '%')
    print('Core freq: ' .. data['freq'] .. 'MHz')
    print('Memory freq: ' .. data['memFreq'] .. 'MHz')
    print('Temp: ' .. data['tempCelcius'] .. 'C')
    print('Throttle Temp: ' .. data['slowdownTempCelcius'] .. 'C')
    print('Shutdown Temp: ' .. data['shutdownTempCelcius'] .. 'C')
end
-- print(nvml_query_device_info('ea', 3))
nvml.close()
nvml.close()
print(nvml.is_initialized(1, 2, 3))
